### PR TITLE
validate file based arguments point to existing files / directories

### LINKED ISSUE #449: do not ignore incorrect localCheckoutDir
### Jenkins and plugins versions report

<details>
  <summary>if the local checkout directory is provided but does not exist no error is raised</summary>

In reviewing #484 I was alerted to the fact that the pct considers the [local checkout directory to not be provided if it does not exist](https://github.com/jenkinsci/plugin-compat-tester/blob/e00a890bf4a9255ba630e5910719121ce9f5a7a6/src/main/java/org/jenkins/tools/test/PluginCompatTester.java#L613-L615).

This violates the principle of least surprise - it the option is provided yet the path does not exist the pct should return with an error rather than continuing on to test something that may not be what was intended.

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

windows - but this is cross platform.

### Reproduction steps

run the pct with the localCheckout option set to a non existant directory

e.g.
`java -Xmx1g -jar target\plugins-compat-tester-cli.jar -workDirectory c:\workarea\source\github\cloudbees\unified-release\output-caffeine-api\work -reportFile c:\workarea\source\github\cloudbees\unified-release\output-caffeine-api\out\report.xml -war c:\workarea\source\github\cloudbees\unified-release\products\core-cm\target\core-cm.war -storeAll -fallbackGitHubOrganization jenkinsci-cert -hookPrefixes com.cloudbees.hooks -externalHooksJars c:\workarea\source\github\cloudbees\unified-release\tests\cb-pct-hooks\target\cb-pct-hooks.jar -includePlugins caffeine-api -mavenPropertiesFile c:\workarea\source\github\cloudbees\unified-release\output-caffeine-api\work\maven.properties -mavenProperties jenkins.version=2.375.3-cb-1 -localCheckoutDir c:\workarea\does-not-exist` 

note that `c:\workarea\does-not-exist` does not exist :)

### Expected Results

pct fails

### Actual Results

pct runs and passes

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by jtnord**
if a File based paramter is set (excluding workingDir which we create) then parsing the arg will fail early rather than continuing and then erroring (or silently swallowing it) later in the run

fixes #449

tested with various arg combintions with option args present and valid, not present, and present and invalid

```
java -jar target\plugins-compat-tester-cli.jar --working-dir=work --war=LICENSE.txt --mvn=LICENSE.txt --external-hooks-jars=LICENSE.txt,pom.xml --maven-settings=sdf
Invalid value for option '--maven-settings': Specified file sdf does not exist
Usage: pct [-hV] [--[no-]fail-fast]
...
```

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Review by basil — APPROVED** [review]
Very nice

File: src/main/java/org/jenkins/tools/test/PluginCompatTesterCli.java [hunk 1]
```diff
@@ -104,13 +106,17 @@ public class PluginCompatTesterCli implements Callable<Integer> {
     private String fallbackGitHubOrganization;
 
     @CheckForNull
-    @CommandLine.Option(names = "--mvn", description = "The path to the Maven executable.")
+    @CommandLine.Option(
+            names = "--mvn",
+            description = "The path to the Maven executable.",
+            converter = ExistingFileTypeConverter.class)
```
Comment (jtnord) [inline src/main/java/org/jenkins/tools/test/PluginCompatTesterCli.java:112]: arguably this is incorrect but we already call [`getAbosultePath`](https://github.com/jenkinsci/plugin-compat-tester/blob/943a678afd97f11f662203ebe33b30b7601163f9/src/main/java/org/jenkins/tools/test/maven/ExternalMavenRunner.java#L61) so we can not pass in something that we expect to be on the path.

**Comment by jtnord** [comment]
java17 build seems to be failing in the smoke test with  `/tmp/junit7880214900056192275/text-finder failed with exit status 143`

This smells like a used to much memory and I killed you issue.  given we are using multiple JVMs (maven, surefire, running the pct which runs maven and builds....) I expect we have an unconstrained JVM or 2 in the loop.

**Comment by jtnord** [comment]
test run timing 

|     |  [`master`](https://ci.jenkins.io/blue/organizations/jenkins/jenkinsci-libraries%2Fplugin-compat-tester/detail/master/273/pipeline/74) (one less test) | [this pr](https://ci.jenkins.io/blue/organizations/jenkins/jenkinsci-libraries%2Fplugin-compat-tester/detail/PR-483/6/pipeline/52)
| ----------- | ----------- | ----------- |
| Java 11      | 2m 07s  |  2m 34s  |
| Java 17      | 3m 27s   |  2m 29s  |

**Review by basil — APPROVED** [review]
